Feature/form styles and functionality
HackYourFuture-CPH/class-25-erikson pull request #30
Opened 2023-10-12 08:16 UTC by narendra28051991

## Ticket Link: [ID](https://www.meistertask.com/app/task/ID)
[ID: 8P8eVMhE](https://www.meistertask.com/app/task/8P8eVMhE)

## 📝 Description
Created one style sheet for all the forms

- [x] Description of work
The three forms will be responsive for all screen resolutions.

## ⚠️ Notes

## 🎉 Demos

2023-10-13 12:59 UTC, Nelia11 reviewed
Looks good to me!

2023-10-14 10:24 UTC, jawkha requested changes

2023-10-14 10:24 UTC, jawkha commented on frontend/src/types/component.d.ts
Any reason for using `snake case` for naming some properties and `camel case` for others?

2023-10-14 10:24 UTC, jawkha commented on frontend/src/pages/myCourses/MyCourses.tsx
Are the courses still not fetched from the database?

2023-10-14 10:52 UTC, narendra28051991 commented on frontend/src/types/component.d.ts
Yes Jawad because of the backend

2023-10-14 13:20 UTC, jawkha approved these changes

2023-10-14 13:22 UTC, jawkha approved these changes

2023-10-14 13:22 UTC, jawkha commented on frontend/src/pages/myCourses/MyCourses.tsx
@narendra28051991 Please create a separate issue for this to ensure that courses are fetched from the database if this is not already covered in another PR.

2023-10-14 13:22 UTC, merged